CFLAGS = -I../include -I../../src/include -I../../src/includepriv -I../helpers/

all: config.t

config.t: ../helpers/test_xmms.o ../../_build_/default/src/clients/lib/xmmsclient/libxmmsclient.so

.PHONY: all
