from waftools.plugin import plugin

def plugin_configure(conf):
    return conf.check_pkg('libpulse-simple', destvar='pulse')

configure, build = plugin('pulse', configure=plugin_configure, needs_lib=True,
                          output_prio=5)
