#!/usr/bin/env perl

use strict;
use warnings;
use IO::File;
use File::Spec::Functions qw/catdir rel2abs/;

my $test = $ARGV[0];

sub src_to_bld { "_build_/default/t/$_[0]" }

my %exec_for = (
        (map {
            (src_to_bld($_) => [$^X, qw{-I t/helpers/lib}, src_to_bld($_)]),
        } qw{
            xmms/bindata.t
            clients/lib/xmmsclient/collparser.t
            clients/lib/perl/class_api.t
            clients/lib/perl/refcnt.t
            clients/lib/perl/collections.t
            clients/lib/perl/result.t
        }),
        (map {
            (src_to_bld($_) => [qw{python}, src_to_bld($_)]),
        } qw{src/indentcheck.t}),
);

my $fh = IO::File->new(catdir(qw/_build_ test_config/), 'r');
my $data = do { local $/ = undef; <$fh> };
my %config = $data =~ /^([^=]+)=(.*)$/mg;

$ENV{LD_LIBRARY_PATH} = rel2abs(catdir($config{TEST_INSTALL_DIR}, $config{PREFIX}, 'lib'));

if (exists $exec_for{$test}) {
    exec @{ $exec_for{$test} };
}

exec $test;
