#!/usr/bin/env perl

use strict;
use warnings;
use TAP::Harness::Color;
use FindBin;

my $harness = TAP::Harness::Color->new({
        exec  => [$^X, './exec_test'],
        timer => 1,
});

# TAP::Harness 0.52 is br0ken
if (TAP::Harness->VERSION >= 0.51 && TAP::Harness->VERSION <= 0.52) {
    my $func_name = '_get_parser_args';
    my $func = TAP::Harness->can($func_name);

    {
        no strict 'refs';
        no warnings 'redefine';

        *{ "TAP::Harness::" . $func_name } = sub {
            my $self = shift;
            my $inherited = $self->$func(@_);

            if (!exists $inherited->{exec}) {
                $inherited->{exec} = [ './exec_test', $_[0] ];
                delete $inherited->{source};
            }

            return $inherited;
        };
    }
}

my @tests = @ARGV || find_tests($FindBin::Bin);
$harness->runtests(@tests);

sub find_tests {
    return
        map  { "_build_/default/t/$_" }
        qw{
            plugins/xml.t
            plugins/rss.t
            plugins/xspf.t
            plugins/nulstripper.t
            xmms/bindata.t
            xmms/config.t
            xmms/collquery.t
            lib/xmmsipc/parse_url.t
            lib/xmmsutils/unix.t
            clients/lib/xmmsclient/collparser.t
            clients/lib/perl/class_api.t
            clients/lib/perl/refcnt.t
            clients/lib/perl/collections.t
            clients/lib/perl/result.t
            src/indentcheck.t
        };
# broken under TAP::Parser: lib/xmmsipc/client_server.t
# buggy: xmms/clients.t
}
