import Options

types_suite=["xmmsv/t_xmmsv.c", 'xmmsv/t_xmmsv_serialization.c', "xmmsv/t_coll.c"]
server_suite=["server/t_streamtype.c"]
mlib_suite=["server/t_medialib.c"]

def configure(conf):
    conf.check_cc(header_name="CUnit/CUnit.h", mandatory=True)
    conf.check_cc(lib="cunit", uselib_store="cunit", mandatory=True)
    conf.check_cc(lib="ncurses", uselib_store="ncurses")

    code = """
           static void T (void) __attribute__ ((constructor (220)));
           static void T (void) {};
    """
    conf.check_cc(fragment=code, type="cc", msg="Checking for constructor attribute", mandatory=True)

    conf.check_cfg(package='valgrind', uselib_store='valgrind', args='--cflags')

def build(bld):
    obj = bld.new_task_gen('cc', 'staticlib')
    obj.target = 'testutils'
    obj.source = 'utils/jsonism.c utils/value_utils.c utils/coll_utils.c utils/ipc_call.c'
    obj.includes = '. ../src/include'
    obj.uselib = 'glib2'
    obj.install_path = 0

    obj = bld.new_task_gen('cc', 'program')
    obj.target = "test_xmmstypes"
    obj.source = ['runner/main.c', 'runner/valgrind.c'] + types_suite
    obj.includes = '. ../ runner/ ../src ../src/include'
    obj.uselib_local = 'xmmstypes xmmsutils'
    obj.uselib = 'cunit ncurses valgrind DISABLE_WRITESTRINGS'
    obj.install_path = None

    obj = bld.new_task_gen('cc', 'program')
    obj.target = "test_server"
    obj.source = ['runner/main.c', 'runner/valgrind.c', '../src/xmms/streamtype.c', '../src/xmms/object.c'] + server_suite
    obj.includes = '. ../ runner/ ../src ../src/includepriv ../src/include'
    obj.uselib_local = 'xmmstypes xmmsutils s4'
    obj.uselib = 'cunit ncurses valgrind glib2 gthread2 DISABLE_WRITESTRINGS'
    obj.install_path = None

    bld.new_task_gen(
        source=['../src/ipc.xml', '../src/xmms/medialib_ipc.py'],
        target="medialib_ipc.c",
        rule='${PYTHON} ${SRC[1].abspath()} > ${TGT}',
        before='cc')

    bld.new_task_gen(
        source=['../src/ipc.xml', '../src/xmms/config_ipc.py'],
        target="config_ipc.c",
        rule='${PYTHON} ${SRC[1].abspath()} > ${TGT}',
        before='cc')

    bld.new_task_gen(
        source=['../src/ipc.xml', '../src/xmms/visualization/object_ipc.py'],
        target='object_ipc.c',
        rule='${PYTHON} ${SRC[1].abspath()} > ${TGT}',
        before='cc')

    obj = bld.new_task_gen('cc', 'program')
    obj.target = "test_medialib"
    obj.source = [ 'runner/main.c', 'runner/valgrind.c' ] + mlib_suite
    obj.includes = '. ../ runner/ ../src ../src/includepriv ../src/include'
    obj.uselib_local = 'xmms2core xmmsipc xmmssocket xmmstypes xmmsutils s4 testutils'
    obj.uselib = 'cunit ncurses valgrind glib2 gmodule2 gthread2 DISABLE_WRITESTRINGS'
    obj.install_path = None

    obj = bld.new_task_gen('cc', 'program')
    obj.target = "test_playlist"
    obj.source = [ 'runner/main.c', 'runner/valgrind.c', 'server/t_playlist.c']
    obj.includes = '. ../ runner/ ../src ../src/includepriv ../src/include'
    obj.uselib_local = 'xmms2core xmmsipc xmmssocket xmmstypes xmmsutils s4 testutils'
    obj.uselib = 'cunit ncurses valgrind glib2 gmodule2 gthread2 DISABLE_WRITESTRINGS'
    obj.install_path = None

    obj = bld.new_task_gen('cc', 'program')
    obj.target = "medialib-runner"
    obj.source = [ 'server/medialib-runner.c' ]
    obj.includes = '. ../ runner/ ../src ../src/includepriv ../src/include'
    obj.uselib_local = 'xmmsipc xmmssocket xmmstypes xmmsutils s4 testutils'
    obj.uselib = 'glib2 gmodule2 gthread2 DISABLE_WRITESTRINGS'
    obj.install_path = None

def set_options(o):
    pass
