/* generated by genipc.py */

#include "xmmsclient/xmmsclient.h"

void
process_req (xmmsc_request_t *req, xmms_ipc_msg_t *msg)
{
	int obj, cmd, type;

	obj = xmms_ipc_msg_get_object (msg);
	cmd = xmms_ipc_msg_get_cmd (msg);
	switch (obj) {
		case XMMSC_IPC_OBJECT_MAIN:
			if ((cmd == XMMSC_MAIN_METHOD_HELLO)) {
			}
				unsigned int *helloretval;
				helloretval = deserialize_main_cmd_hello (msg);
				if (req->cb)
					req->cb (helloretval);
			if ((cmd == XMMSC_MAIN_METHOD_QUIT)) {
			}
			break;
		case XMMSC_IPC_OBJECT_PLAYLIST:
			if ((cmd == XMMSC_PLAYLIST_METHOD_CREATE)) {
			}
			if ((cmd == XMMSC_PLAYLIST_METHOD_ADD_ID)) {
			}
			if ((cmd == XMMSC_PLAYLIST_METHOD_LIST)) {
			}
				char ** *listretval;
				listretval = deserialize_playlist_cmd_list (msg);
				if (req->cb)
					req->cb (listretval);
			if ((cmd == XMMSC_PLAYLIST_METHOD_SHUFFLE)) {
			}
			if ((cmd == XMMSC_PLAYLIST_METHOD_LOAD)) {
			}
			if ((cmd == XMMSC_PLAYLIST_METHOD_CLEAR)) {
			}
			if ((cmd == XMMSC_PLAYLIST_METHOD_SET_POS_REL)) {
			}
			if ((cmd == XMMSC_PLAYLIST_PROPERTY_POS) && type == 0) {
			}
			break;
		case XMMSC_IPC_OBJECT_OUTPUT:
			if ((cmd == XMMSC_OUTPUT_METHOD_START)) {
			}
			if ((cmd == XMMSC_OUTPUT_METHOD_STOP)) {
			}
			if ((cmd == XMMSC_OUTPUT_METHOD_STATUS)) {
			}
				int *statusretval;
				statusretval = deserialize_output_cmd_status (msg);
				if (req->cb)
					req->cb (statusretval);
			if ((cmd == XMMSC_OUTPUT_METHOD_PAUSE)) {
			}
			if ((cmd == XMMSC_OUTPUT_METHOD_KILL)) {
			}
			if ((cmd == XMMSC_OUTPUT_PROPERTY_PLAYTIME) && type == 0) {
			}
			break;
		default:
			fprintf(stderr, "Error, incorrect IPC object detected.\n");
			break;
	}
}
