/* generated by genipc.py */

#include "xmmsclient/xmmsclient.h"

unsigned int*
deserialize_main_cmd_hello (xmms_ipc_msg_t *msg )
{
	unsigned int *retvar;
	retvar = malloc(sizeof(unsigned int));
	xmms_ipc_msg_get_uint32 (msg, retvar);
	return retvar;
}

void
deserialize_main_cmd_quit (xmms_ipc_msg_t *msg )
{
}

void
deserialize_playlist_cmd_create (xmms_ipc_msg_t *msg )
{
}

void
deserialize_playlist_cmd_add_id (xmms_ipc_msg_t *msg )
{
}

char ***
deserialize_playlist_cmd_list (xmms_ipc_msg_t *msg )
{
	char ** *retvar;
	retvar = malloc(sizeof(char **));
	xmms_ipc_msg_get_uint32 (msg, retvar);
	return retvar;
}

void
deserialize_playlist_cmd_shuffle (xmms_ipc_msg_t *msg )
{
}

void
deserialize_playlist_cmd_load (xmms_ipc_msg_t *msg )
{
}

void
deserialize_playlist_cmd_clear (xmms_ipc_msg_t *msg )
{
}

void
deserialize_playlist_cmd_set_pos_rel (xmms_ipc_msg_t *msg )
{
}

void
deserialize_output_cmd_start (xmms_ipc_msg_t *msg )
{
}

void
deserialize_output_cmd_stop (xmms_ipc_msg_t *msg )
{
}

int*
deserialize_output_cmd_status (xmms_ipc_msg_t *msg )
{
	int *retvar;
	retvar = malloc(sizeof(int));
	xmms_ipc_msg_get_int32 (msg, retvar);
	return retvar;
}

void
deserialize_output_cmd_pause (xmms_ipc_msg_t *msg )
{
}

void
deserialize_output_cmd_kill (xmms_ipc_msg_t *msg )
{
}

