# encoding: utf-8
#
# WAF build scripts for XMMS2
# Copyright (C) 2006-2012 XMMS2 Team
#

def build(bld):
    source = """
    coll.c
    xmmsv_general.c
    xmmsv_list.c
    xmmsv_dict.c
    xmmsv_bitbuffer.c
    xmmsv_copy.c
    xmmsv_build.c
    xmmsv_util.c
    xlist.c
    value_serialize.c
    """.split()

    bld(features = 'c cstlib',
        target = 'xmmstypes',
        source = source,
        includes = '. ../../.. ../../include ../../includepriv',
        install_path = None
        )


def configure(conf):
    return True


def options(opt):
    pass
