# encoding: utf-8
#
# WAF build scripts for XMMS2
# Copyright (C) 2006-2012 XMMS2 Team
#

def build(bld):
    source = """
    xmmsv_general.c
    xmmsv_list.c
    xmmsv_dict.c
    xmmsv_coll.c
    xmmsv_bitbuffer.c
    xmmsv_copy.c
    xmmsv_build.c
    xmmsv_util.c
    xmmsv_to_json.c
    xmmsv_from_json.c
    xlist.c
    value_serialize.c
    """.split()

    bld(features = "c",
        target = "libjson",
        source = "json.c",
        uselib = "DISABLE_MISSINGPROTOTYPES DISABLE_WRITESTRINGS",
        install_path = None,
        )

    bld(features = 'c cstlib',
        target = 'xmmstypes',
        source = source,
        add_objects = "libjson",
        includes = '. ../../.. ../../include ../../includepriv',
        install_path = None
        )

def configure(conf):
    return True

def options(opt):
    pass
