#!/usr/bin/env perl

use strict;
use warnings;

my $test = $ARGV[0];

my %exec_for = (
        (map {
            $_ => [$^X, qw{-I helpers/lib}, $_],
        } qw{
            xmms/bindata.t
            clients/lib/xmmsclient/collparser.t
            clients/lib/perl/class_api.t
            clients/lib/perl/refcnt.t
            clients/lib/perl/collections.t
            clients/lib/perl/result.t
        }),
        (map {
            $_ => [qw{python}, $_],
        } qw{src/indentcheck.t}),
);

if (exists $exec_for{$test}) {
    exec @{ $exec_for{$test} };
}

exec $test;
