from waftools.plugin import plugin

def plugin_configure(conf):
    if not conf.check_cfg(package="kate", uselib_store="kate", args="--cflags --libs"):
        return False
    if not conf.check_cfg(package="ogg", uselib_store="ogg", args="--cflags --libs"):
        return False
    return True

configure, build = plugin("kate", configure=plugin_configure, libs=["kate", "ogg"])
